trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  terraformVersion: '1.6.6'

steps:
# -----------------------------------
# Download SSH public key (secure file)
# -----------------------------------
- task: DownloadSecureFile@1
  name: sshkey
  inputs:
    secureFile: id_rsa.pub

# -----------------------------------
# Read SSH key & expose to Terraform
# -----------------------------------
# - powershell: |
#     $key = Get-Content "$(sshkey.secureFilePath)" -Raw
#     $key = $key.Trim()
#     Write-Host "##vso[task.setvariable variable=TF_VAR_ssh_public_key]$key"
#   displayName: 'Set SSH public key for Terraform'

- powershell: |
    $key = Get-Content "$(sshkey.secureFilePath)" -Raw

    # Remove BOM if present
    $key = $key -replace "^\uFEFF", ""

    # Collapse to a single line (Azure requires one line)
    $key = $key -replace "`r", "" -replace "`n", ""

    # Trim spaces
    $key = $key.Trim()

    Write-Host "Final SSH key:"
    Write-Host $key.Substring(0,20)

    Write-Host "##vso[task.setvariable variable=TF_VAR_ssh_public_key]$key"
  displayName: 'Sanitize and set SSH public key'

# -----------------------------------
# Install Terraform
# -----------------------------------
- task: TerraformInstaller@1
  displayName: 'Install Terraform'
  inputs:
    terraformVersion: $(terraformVersion)

# -----------------------------------
# Terraform Init
# -----------------------------------
- task: TerraformTaskV4@4
  displayName: 'Terraform Init'
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'azurerm-sc-terraform'
    backendAzureRmResourceGroupName: 'tfstate-rg'
    backendAzureRmStorageAccountName: 'tfstateazmig'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'todoapp.tfstate'
    workingDirectory: '$(System.DefaultWorkingDirectory)'

# -----------------------------------
# Terraform Plan
# -----------------------------------
- task: TerraformTaskV4@4
  displayName: 'Terraform Plan'
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'azurerm-sc-terraform'
    workingDirectory: '$(System.DefaultWorkingDirectory)'

# -----------------------------------
# Terraform Apply
# -----------------------------------
- task: TerraformTaskV4@4
  displayName: 'Terraform Apply'
  inputs:
    provider: 'azurerm'
    command: 'apply'
    environmentServiceNameAzureRM: 'azurerm-sc-terraform'
    commandOptions: '-auto-approve'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
